<?php

namespace App\helpers;

use App\core\Helper;

class ImageHelper extends Helper
{
    /**
     * Path to images folder
     *
     * @var string
     */
    protected string $path;

    /**
     * Valid image extensions
     *
     * @var array
     */
    protected array $validExtensions = ["png", "jpg", "jpeg"];

    /**
     * Contains errors generated by the class
     *
     * @param string $errors
     */
    public string $errors = "";

    /**
     * Max size of the image 
     *
     * @var integer
     */
    protected float $maxImageSize = 2e6;
    # Max Image Size: 1.9 MB

    public const IMAGE_UPLOAD_LIMIT = 5;

    public function __construct(
        public string $destination = ""
    ) {
        // $this->path = __DIR__ . "/../crm/images/{$this->destination}/";
    }

    public function getMaxImageSize()
    {
        return $this->maxImageSize;
    }

    public function getValidExtensions(): array
    {
        return $this->validExtensions;
    }

    /**
     * Uploads images to desired destination
     *
     * @param ?array $file
     * @param boolean $returnFileName
     * @return ?bool|?string
     */
    function uploadImage(?array $image, string $path, string|null $desirableImgName = null)
    {
        if (!isset($image["name"])) return null;

        $size = $image['size'];
        $error = $image['error'];
        $tmp_name = $image['tmp_name'];
        $file_name = $image['name'];

        $tmpExtension = explode('.', $file_name);
        $file_ext = strtolower(end($tmpExtension));

        $newFileName = "ICUC-" . uniqid() . "-" . date("Y_m_d") . ".$file_ext";

        $newFileName = $desirableImgName == null ? $newFileName : $desirableImgName; 

        $new_destination = $path . $newFileName;

        if (is_array($image)) {
            if (in_array($file_ext, $this->validExtensions)) {
                if (!$error) {
                    if ($size < $this->maxImageSize) {
                        move_uploaded_file($tmp_name, $new_destination);
                    } else {
                        $this->errors = "The File You Uploaded Is Too Large";
                        return false;
                    }
                } else {
                    $this->errors = "An Error Occured..";
                    return false;
                }
            } else {
                $this->errors = "File of type '$file_ext' is not allowed";
                return false;
            }
        } else {
            return false;
        }

        return $newFileName;
    }

    /**
     * Undocumented function
     *
     * @param array|null $imageName
     * @return true
     */
    final public function renameImage(string $oldname, string $newname)
    {
        $array_file_name = explode('.', $oldname);
        $oldname = $this->path . $oldname;
        $file_extension = end($array_file_name);
        $filename = $newname . '.' . $file_extension;
        $newname = $this->path . $newname . '.' . $file_extension;

        if (rename($oldname, $newname)) {
            $fb = true;
            $this->errors = $filename;
        } else {
            $fb = false;
            $this->errors = 'Error renaming file';
        }

        return $fb;
    }

    /**
     * Deletes images
     *
     * @param string $filename
     * @return bool
     */
    public function removeImage(string $path, string $filename)
    {
        @unlink($path.$filename);
        return true; 
    }
}
